/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "AdMesh SDK Documentation",
  "tagline": "AI Agent Integration Guide for Product Recommendations",
  "favicon": "img/favicon.ico",
  "url": "https://docs.useadmesh.com",
  "baseUrl": "/",
  "organizationName": "GouniManikumar12",
  "projectName": "admesh-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/GouniManikumar12/admesh-docs/tree/main/docs/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-C30NMN6PCH",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/admesh-social-card.jpg",
    "metadata": [
      {
        "name": "keywords",
        "content": "AdMesh, AI, SDK, product recommendations, agent integration, API"
      },
      {
        "name": "description",
        "content": "Professional AI agent integration platform for product recommendations"
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:site_name",
        "content": "AdMesh Documentation"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "AdMesh",
      "hideOnScroll": false,
      "style": "primary",
      "items": [
        {
          "href": "https://storybook.useadmesh.com",
          "label": "Live Examples",
          "position": "left",
          "target": "_blank"
        },
        {
          "href": "https://useadmesh.com/agents#earnings-calculator",
          "label": "Earnings Calculator",
          "position": "right",
          "target": "_blank",
          "className": "navbar__link--earnings"
        },
        {
          "href": "https://useadmesh.com",
          "label": "Dashboard",
          "position": "right"
        },
        {
          "type": "dropdown",
          "label": "SDKs",
          "position": "right",
          "items": [
            {
              "href": "https://github.com/GouniManikumar12/admesh-python",
              "label": "Python SDK",
              "target": "_blank"
            },
            {
              "href": "https://github.com/GouniManikumar12/admesh-typescript",
              "label": "TypeScript SDK",
              "target": "_blank"
            },
            {
              "href": "https://github.com/GouniManikumar12/admesh-ui-sdk",
              "label": "UI SDK",
              "target": "_blank"
            }
          ]
        }
      ]
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/getting-started/overview"
            },
            {
              "label": "Ad Units",
              "to": "/ad-units/overview"
            },
            {
              "label": "API Reference",
              "to": "/api/authentication"
            },
            {
              "label": "Examples",
              "to": "/examples/ai-assistant"
            }
          ]
        },
        {
          "title": "SDKs & Tools",
          "items": [
            {
              "label": "Python SDK",
              "href": "https://github.com/GouniManikumar12/admesh-python",
              "target": "_blank"
            },
            {
              "label": "TypeScript SDK",
              "href": "https://github.com/GouniManikumar12/admesh-typescript",
              "target": "_blank"
            },
            {
              "label": "UI SDK",
              "href": "https://github.com/GouniManikumar12/admesh-ui-sdk",
              "target": "_blank"
            },
            {
              "label": "Live Examples",
              "href": "https://storybook.useadmesh.com",
              "target": "_blank"
            }
          ]
        },
        {
          "title": "Platform",
          "items": [
            {
              "label": "AdMesh Dashboard",
              "href": "https://useadmesh.com",
              "target": "_blank"
            },
            {
              "label": "Earnings Calculator",
              "href": "https://useadmesh.com/agents#earnings-calculator",
              "target": "_blank"
            },
            {
              "label": "Agent Signup",
              "href": "https://useadmesh.com/agents",
              "target": "_blank"
            },
            {
              "label": "Brand Signup",
              "href": "https://useadmesh.com/brands",
              "target": "_blank"
            }
          ]
        },
        {
          "title": "Community & Support",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/GouniManikumar12",
              "target": "_blank"
            },
            {
              "label": "Support",
              "href": "mailto:mani@useadmesh.com"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/manikumargouni",
              "target": "_blank"
            },
            {
              "label": "Status",
              "href": "https://status.useadmesh.com",
              "target": "_blank"
            }
          ]
        }
      ],
      "copyright": "\n          <div style=\"margin-top: 2rem; padding-top: 1.5rem; border-top: 1px solid var(--ifm-border-color); text-align: center;\">\n            <p style=\"margin-bottom: 0.5rem; color: var(--ifm-color-content-secondary);\">\n              Have a question? <a href=\"mailto:mani@useadmesh.com\" style=\"color: var(--ifm-color-primary); text-decoration: none;\">Contact us</a> or connect on <a href=\"https://www.linkedin.com/in/manikumargouni\" target=\"_blank\" style=\"color: var(--ifm-color-primary); text-decoration: none;\">LinkedIn</a>\n            </p>\n            <p style=\"margin: 0; color: var(--ifm-color-content-secondary); font-size: 0.875rem;\">\n              Copyright © 2025 AdMesh. All rights reserved.\n            </p>\n          </div>\n        "
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "python",
        "typescript",
        "javascript"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "W5X8L8ZZ8V",
      "apiKey": "8a928420719b5fe16b30b8592dd55e2e",
      "indexName": "admesh-docs",
      "contextualSearch": true,
      "externalUrlRegex": "external\\.com|domain\\.com",
      "replaceSearchResultPathname": {
        "from": "/docs/",
        "to": "/"
      },
      "searchParameters": {
        "facetFilters": [],
        "hitsPerPage": 10,
        "attributesToRetrieve": [
          "hierarchy",
          "content",
          "anchor",
          "url",
          "url_without_anchor",
          "type",
          "title",
          "category",
          "keywords",
          "description"
        ],
        "attributesToSnippet": [
          "content:15",
          "description:10"
        ],
        "attributesToHighlight": [
          "hierarchy",
          "content",
          "title",
          "keywords"
        ],
        "snippetEllipsisText": "...",
        "typoTolerance": true,
        "ignorePlurals": true,
        "removeStopWords": true
      },
      "searchPagePath": "search",
      "insights": false,
      "placeholder": "Search AdMesh docs (Press / to focus)",
      "searchBoxProps": {
        "placeholder": "Search documentation..."
      }
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
